CREATE TABLE IF NOT EXISTS Users(
    ID SERIAL NOT NULL PRIMARY KEY,
    Username TEXT NOT NULL UNIQUE,
    Password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Links(
    ID SERIAL NOT NULL PRIMARY KEY,
    Title TEXT,
    Address TEXT,
    UserID INT REFERENCES Users(ID)
);
